# Generated by Django 5.2.6 on 2025-09-28 03:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='designationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('HRA_percent', models.FloatField(max_length=100, unique=True)),
                ('DA_percent', models.FloatField(default=0)),
                ('TA_percent', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='employeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=100, null=True)),
                ('emp_id', models.IntegerField(null=True)),
                ('emp_city', models.CharField(max_length=100, null=True)),
                ('emp_gender', models.CharField(max_length=100, null=True)),
                ('emp_DOB', models.DateField(blank=True, null=True)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_phone', models.CharField(max_length=15, null=True)),
                ('emp_address', models.TextField(blank=True, null=True)),
                ('basic_salary', models.FloatField(max_length=100, null=True)),
                ('bonus', models.FloatField(default=0, max_length=100, null=True)),
                ('overtime', models.FloatField(default=0, max_length=100, null=True)),
                ('total_salary', models.FloatField(default=0, max_length=100, null=True)),
                ('date_of_joining', models.DateField(default=django.utils.timezone.now)),
                ('designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.designationmodel')),
            ],
        ),
    ]
