# Generated by Django 5.2.6 on 2025-09-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemodel',
            old_name='total_salary',
            new_name='salary',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='emp_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
